//! Opening lines for match play.
//!
//! Games must not all start from the same position. Two engines playing the
//! startpos repeatedly produce a handful of distinct games and the "variance"
//! of the match is then mostly an artefact of how often each one is repeated —
//! the sample size is a lie. A book of balanced, well-known openings makes
//! each pair an independent draw from a spread of position types.
//!
//! Deliberately *not* generated by our own engine: a book of "positions our
//! eval scores near zero" would select for openings that suit our eval, which
//! is precisely the thing under measurement. These are book lines from theory,
//! 4-8 plies, roughly balanced, spanning open, closed, semi-open and flank.
//!
//! Every line is verified legal by a unit test, so a typo here is a test
//! failure, not a corrupted match.

/// Built-in book, as UCI move sequences from the start position.
pub const LINES: &[&str] = &[
    // --- 1.e4 e5
    "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6",       // Ruy Lopez, Morphy
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5",       // Italian
    "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4",       // Scotch
    "e2e4 e7e5 g1f3 b8c6 b1c3 g8f6",       // Four Knights
    "e2e4 e7e5 g1f3 g8f6",                 // Petroff
    "e2e4 e7e5 g1f3 d7d6 d2d4 e5d4",       // Philidor
    "e2e4 e7e5 b1c3 g8f6 g2g3 f8c5",       // Vienna
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5",       // King's Gambit accepted
    "e2e4 e7e5 f1c4 g8f6 d2d3 c7c6",       // Bishop's Opening
    // --- Sicilian
    "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6", // Open Sicilian
    "e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6", // Sicilian, four knights
    "e2e4 c7c5 g1f3 e7e6 d2d4 c5d4 f3d4 b8c6", // Taimanov
    "e2e4 c7c5 b1c3 b8c6 g2g3 g7g6",           // Closed Sicilian
    "e2e4 c7c5 c2c3 d7d5 e4d5 d8d5",           // Alapin
    // --- other semi-open
    "e2e4 e7e6 d2d4 d7d5 b1c3 g8f6",       // French, Classical
    "e2e4 e7e6 d2d4 d7d5 e4e5 c7c5",       // French, Advance
    "e2e4 c7c6 d2d4 d7d5 b1c3 d5e4",       // Caro-Kann
    "e2e4 c7c6 d2d4 d7d5 e4e5 c8f5",       // Caro-Kann, Advance
    "e2e4 d7d5 e4d5 d8d5 b1c3 d5a5",       // Scandinavian
    "e2e4 g8f6 e4e5 f6d5 d2d4 d7d6",       // Alekhine
    "e2e4 d7d6 d2d4 g8f6 b1c3 g7g6",       // Pirc
    "e2e4 g7g6 d2d4 f8g7 b1c3 d7d6",       // Modern
    "e2e4 b8c6 d2d4 d7d5 b1c3 d5e4",       // Nimzowitsch
    // --- 1.d4 d5
    "d2d4 d7d5 c2c4 e7e6 b1c3 g8f6",       // QGD
    "d2d4 d7d5 c2c4 d5c4 g1f3 g8f6",       // QGA
    "d2d4 d7d5 c2c4 c7c6 g1f3 g8f6",       // Slav
    "d2d4 d7d5 c2c4 e7e6 b1c3 c7c6",       // Semi-Slav
    "d2d4 d7d5 g1f3 g8f6 c1f4 e7e6",       // London
    "d2d4 d7d5 c2c4 c7c5",                 // Austrian
    // --- Indian defences
    "d2d4 g8f6 c2c4 e7e6 b1c3 f8b4",       // Nimzo-Indian
    "d2d4 g8f6 c2c4 e7e6 g1f3 b7b6",       // Queen's Indian
    "d2d4 g8f6 c2c4 g7g6 b1c3 f8g7 e2e4 d7d6", // King's Indian
    "d2d4 g8f6 c2c4 g7g6 b1c3 d7d5",       // Grunfeld
    "d2d4 g8f6 c2c4 c7c5 d4d5 b7b5",       // Benko
    "d2d4 g8f6 c2c4 e7e6 g1f3 f8b4",       // Bogo-Indian
    "d2d4 g8f6 c1g5 f6e4",                 // Trompowsky
    "d2d4 f7f5 g2g3 g8f6 f1g2 e7e6",       // Dutch
    // --- flank
    "c2c4 e7e5 b1c3 g8f6 g1f3 b8c6",       // English, reversed Sicilian
    "c2c4 c7c5 g1f3 g8f6 b1c3 b8c6",       // Symmetrical English
    "c2c4 g8f6 b1c3 e7e6 e2e4 d7d5",       // English, Mikenas
    "g1f3 d7d5 g2g3 g8f6 f1g2 c7c6",       // Reti / KIA
    "g1f3 g8f6 c2c4 g7g6 b1c3 f8g7",       // King's Indian setup
    "b2b3 e7e5 c1b2 b8c6 e2e3 g8f6",       // Larsen
];

/// Parse the built-in book into move lists.
pub fn builtin() -> Vec<Vec<String>> {
    LINES.iter().map(|l| split(l)).collect()
}

/// Load a book from a file: one line per opening, UCI moves separated by
/// spaces. Blank lines and `#` comments are ignored.
pub fn load(path: &str) -> Result<Vec<Vec<String>>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    let lines: Vec<Vec<String>> = text
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|l| !l.is_empty())
        .map(split)
        .collect();
    if lines.is_empty() {
        return Err(format!("{path}: no opening lines"));
    }
    Ok(lines)
}

fn split(line: &str) -> Vec<String> {
    line.split_whitespace().map(|s| s.to_string()).collect()
}
