//! Opening lines for match play.
//!
//! Games must not all start from the same position. Two engines playing the
//! startpos repeatedly produce a handful of distinct games and the "variance"
//! of the match is then mostly an artefact of how often each one is repeated —
//! the sample size is a lie. A book of balanced, well-known openings makes
//! each pair an independent draw from a spread of position types.
//!
//! Deliberately *not* generated by our own engine: a book of "positions our
//! eval scores near zero" would select for openings that suit our eval, which
//! is precisely the thing under measurement. These are book lines from theory,
//! 4-8 plies, roughly balanced, spanning open, closed, semi-open and flank.
//!
//! Every line is verified legal by a unit test, so a typo here is a test
//! failure, not a corrupted match.

use crate::board::{Board, START_FEN};
use crate::chess_move::MoveList;
use crate::movegen::{generate, GenType};

/// Built-in book, as UCI move sequences from the start position.
pub const LINES: &[&str] = &[
    // --- 1.e4 e5
    "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6",       // Ruy Lopez, Morphy
    "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5",       // Italian
    "e2e4 e7e5 g1f3 b8c6 d2d4 e5d4",       // Scotch
    "e2e4 e7e5 g1f3 b8c6 b1c3 g8f6",       // Four Knights
    "e2e4 e7e5 g1f3 g8f6",                 // Petroff
    "e2e4 e7e5 g1f3 d7d6 d2d4 e5d4",       // Philidor
    "e2e4 e7e5 b1c3 g8f6 g2g3 f8c5",       // Vienna
    "e2e4 e7e5 f2f4 e5f4 g1f3 g7g5",       // King's Gambit accepted
    "e2e4 e7e5 f1c4 g8f6 d2d3 c7c6",       // Bishop's Opening
    // --- Sicilian
    "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6", // Open Sicilian
    "e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6", // Sicilian, four knights
    "e2e4 c7c5 g1f3 e7e6 d2d4 c5d4 f3d4 b8c6", // Taimanov
    "e2e4 c7c5 b1c3 b8c6 g2g3 g7g6",           // Closed Sicilian
    "e2e4 c7c5 c2c3 d7d5 e4d5 d8d5",           // Alapin
    // --- other semi-open
    "e2e4 e7e6 d2d4 d7d5 b1c3 g8f6",       // French, Classical
    // 4...Qb6 rather than stopping at 3...c5: from the shorter line the
    // engine walks into Na4 Qa5+ Nc3 Qb6 and repeats -- 146 of 280 games
    // in one R3 cell were the *same* 24-ply draw, and the line drew 80%.
    // Measured over 60 self-games at 0.5+0.005: 63% distinct -> 100%,
    // draws 70% -> 38%.
    "e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 d8b6", // French, Advance
    "e2e4 c7c6 d2d4 d7d5 b1c3 d5e4",       // Caro-Kann
    "e2e4 c7c6 d2d4 d7d5 e4e5 c8f5",       // Caro-Kann, Advance
    "e2e4 d7d5 e4d5 d8d5 b1c3 d5a5",       // Scandinavian
    "e2e4 g8f6 e4e5 f6d5 d2d4 d7d6",       // Alekhine
    "e2e4 d7d6 d2d4 g8f6 b1c3 g7g6",       // Pirc
    "e2e4 g7g6 d2d4 f8g7 b1c3 d7d6",       // Modern
    "e2e4 b8c6 d2d4 d7d5 b1c3 d5e4",       // Nimzowitsch
    // --- 1.d4 d5
    "d2d4 d7d5 c2c4 e7e6 b1c3 g8f6",       // QGD
    "d2d4 d7d5 c2c4 d5c4 g1f3 g8f6",       // QGA
    "d2d4 d7d5 c2c4 c7c6 g1f3 g8f6",       // Slav
    "d2d4 d7d5 c2c4 e7e6 b1c3 c7c6",       // Semi-Slav
    "d2d4 d7d5 g1f3 g8f6 c1f4 e7e6",       // London
    "d2d4 d7d5 c2c4 c7c5",                 // Austrian
    // --- Indian defences
    "d2d4 g8f6 c2c4 e7e6 b1c3 f8b4",       // Nimzo-Indian
    "d2d4 g8f6 c2c4 e7e6 g1f3 b7b6",       // Queen's Indian
    "d2d4 g8f6 c2c4 g7g6 b1c3 f8g7 e2e4 d7d6", // King's Indian
    "d2d4 g8f6 c2c4 g7g6 b1c3 d7d5",       // Grunfeld
    "d2d4 g8f6 c2c4 c7c5 d4d5 b7b5",       // Benko
    "d2d4 g8f6 c2c4 e7e6 g1f3 f8b4",       // Bogo-Indian
    "d2d4 g8f6 c1g5 f6e4",                 // Trompowsky
    "d2d4 f7f5 g2g3 g8f6 f1g2 e7e6",       // Dutch
    // --- flank
    "c2c4 e7e5 b1c3 g8f6 g1f3 b8c6",       // English, reversed Sicilian
    "c2c4 c7c5 g1f3 g8f6 b1c3 b8c6",       // Symmetrical English
    "c2c4 g8f6 b1c3 e7e6 e2e4 d7d5",       // English, Mikenas
    "g1f3 d7d5 g2g3 g8f6 f1g2 c7c6",       // Reti / KIA
    "g1f3 g8f6 c2c4 g7g6 b1c3 f8g7",       // King's Indian setup
    "b2b3 e7e5 c1b2 b8c6 e2e3 g8f6",       // Larsen
];

/// One opening: a start position and the moves played from it.
///
/// Two shapes, because the two book formats in the world are different things.
/// A line of UCI moves starts from the initial position and *is* a sequence of
/// moves, so the PGN it produces is an ordinary game. An EPD/FEN line names a
/// position directly and carries no move history at all — the game starts
/// there, the PGN needs `[FEN]`/`[SetUp]` tags, and its move numbering starts
/// from the FEN's own fullmove counter rather than from 1.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Opening {
    pub start_fen: String,
    pub moves: Vec<String>,
}

impl Opening {
    /// True when the game starts from the initial position, i.e. the PGN needs
    /// no `[FEN]` tag and numbers its moves from 1.
    pub fn from_startpos(&self) -> bool {
        self.start_fen == START_FEN
    }
}

/// Parse the built-in book into openings.
pub fn builtin() -> Vec<Opening> {
    LINES.iter().map(|l| Opening { start_fen: START_FEN.to_string(), moves: split(l) }).collect()
}

/// The 4000-line book every match uses unless `--book` says otherwise.
///
/// It is compiled in rather than read from disk because the binary gets copied
/// to the cluster on its own, and a default that depends on a file sitting
/// beside it is the same failure that made `chess bench` report two different
/// node counts depending on whether `quad.nnue` was there.
///
/// Why 4000 lines and not the 43 of `builtin`: the harness computes
/// `SE = sqrt(var(pair scores) / n_pairs)`, which assumes pairs are
/// independent. With 43 openings and 3000 pairs each line is replayed ~70
/// times, and any change worth different amounts in different openings makes
/// that assumption false -- measured design effect 3.27 at R1, so the printed
/// interval was 1.8x too narrow. With more lines than pairs nothing repeats
/// and the printed SE is the honest one. LEDGER 111 and 112.
pub fn default_book() -> Vec<Opening> {
    const LICH: &str = include_str!("../books/lich.epd");
    LICH.lines()
        .filter_map(|l| {
            let l = l.split('#').next().unwrap_or("").trim();
            if l.is_empty() { None } else { Some(parse_line(l).expect("bad line in books/lich.epd")) }
        })
        .collect()
}

/// Load a book from a file. Two formats, detected per line:
///
/// * **UCI moves** — `e2e4 e7e5 g1f3`, played from the initial position.
/// * **EPD / FEN** — `rnbq.../... w KQkq - 0 1`, the game starts there.
///
/// The formats are told apart by the `/` that every FEN's piece placement has
/// and no UCI move can contain, so one file cannot be read as the other by
/// accident. EPD opcodes after the position (`;` in Stockfish's books, `[0.0]`
/// in lichess's) are ignored, as are blank lines and `#` comments.
///
/// Every line is validated here rather than mid-match: a book that cannot be
/// parsed is a setup mistake, and finding it 40 minutes into a run costs the
/// run. FEN lines are additionally checked to be legal positions with a move
/// available, which is what `every_book_line_is_legal` does for the built-in.
pub fn load(path: &str) -> Result<Vec<Opening>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    let mut out = Vec::new();
    for (n, raw) in text.lines().enumerate() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        out.push(parse_line(line).map_err(|e| format!("{path}:{}: {e}", n + 1))?);
    }
    if out.is_empty() {
        return Err(format!("{path}: no opening lines"));
    }
    Ok(out)
}

/// One book line, either format. Public so a caller can validate a single
/// line without writing a file.
pub fn parse_line(line: &str) -> Result<Opening, String> {
    // `generate` reads the magic tables, which return EMPTY before they are
    // built -- so an uninitialised caller would see every slider vanish and
    // every position look stalemated. `Once`-guarded, so this is free after the
    // first call and correct on the zeroth.
    crate::attacks::init();
    let first = line.split_whitespace().next().unwrap_or("");
    if !first.contains('/') {
        return Ok(Opening { start_fen: START_FEN.to_string(), moves: split(line) });
    }
    // An EPD record is a FEN whose last two fields may be missing, followed by
    // opcodes. Cut the opcodes off first: `;` starts them in Stockfish's books,
    // `[` in lichess's (`... - 0 3 [0.0]`).
    let body = line
        .split(';').next().unwrap_or("")
        .split('[').next().unwrap_or("")
        .trim();
    let f: Vec<&str> = body.split_whitespace().collect();
    if f.len() < 4 {
        return Err(format!("FEN needs at least 4 fields, got {}: '{body}'", f.len()));
    }
    // EPD omits the halfmove and fullmove counters; a FEN has them. Take them
    // only when they really are numbers, so a stray opcode cannot become one.
    let hm = f.get(4).and_then(|s| s.parse::<u32>().ok()).unwrap_or(0).min(100);
    let fm = f.get(5).and_then(|s| s.parse::<u32>().ok()).unwrap_or(1).max(1);
    let fen = format!("{} {} {} {} {hm} {fm}", f[0], f[1], f[2], f[3]);
    let board = Board::from_fen(&fen)?;
    let mut list = MoveList::new();
    generate(&board, GenType::All, &mut list);
    if list.is_empty() {
        return Err(format!("position has no legal move: '{fen}'"));
    }
    Ok(Opening { start_fen: fen, moves: Vec::new() })
}

fn split(line: &str) -> Vec<String> {
    line.split_whitespace().map(|s| s.to_string()).collect()
}
